name: Build GUI (MacOS x64)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-pornfetch-gui-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application
        run: |
          mkdir deploy
          shopt -s extglob
          mv !(deploy|venv) deploy/
          cd deploy
          source ../venv/bin/activate
          pyside6-deploy -c src/build/pysidedeploy_macos.spec main.py

      - name: List output directory
        run: |
          ls -R deploy/

      - name: Archive macOS build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-macos
          path: deploy/main.app

  create-release:
    needs: build-pornfetch-gui-linux-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: pyside6-application-x64
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v1.0.0-automated-${{ github.run_number }}
          release_name: Automated Release v1.0.0-${{ github.run_number }}
          body: |
            This is an automated release generated by the CI/CD pipeline.
          draft: false
          prerelease: false

      - name: Upload Linux x64 artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/main.bin
          asset_name: PornFetch_GUI_Linux_x64.bin
          asset_content_type: application/octet-stream