name: Build PySide6 Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-pornfetch-gui-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application for x64
        run: |
          mkdir deploy
          shopt -s extglob
          mv !(deploy|venv) deploy/  # Ensure venv is not moved
          cd deploy
          pwd
          ls -la
          source ../venv/bin/activate
          pyside6-deploy

      - name: Archive x64 build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-x64
          path: deploy/main.bin

  build-pornfetch-gui-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          .\\venv\\Scripts\\activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application for Windows x64
        run: |
          mkdir deploy
          Get-ChildItem -Path . -Exclude deploy,venv | Move-Item -Destination deploy
          cd deploy
          ..\venv\Scripts\activate
          echo "yes" | pyside6-deploy --extra-modules=QtCore,QtWidgets,QtGui

      - name: Archive Windows x64 build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-windows-x64
          path: deploy/main.exe

  build-pornfetch-gui-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application
        run: |
          mkdir deploy
          shopt -s extglob
          mv !(deploy|venv) deploy/
          cd deploy
          source ../venv/bin/activate
          pyside6-deploy

      - name: List output directory
        run: |
          ls -R deploy/

      - name: Archive macOS build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-macos
          path: deploy/pyside_app_demo.app

  build-pornfetch-cli-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements_cli.txt
      - name: Build Porn Fetch (CLI - Windows - X64) (PyInstaller)
        run: |
          pyinstaller -F Porn_Fetch_CLI.py

      - name: Archive Porn Fetch CLI (Windows X64) build
        uses: actions/upload-artifact@v2
        with:
          name: PornFetch_CLI_Linux_x64
          path: dist/Porn_Fetch_CLI.exe

  build-pornfetch-cli-windows-x32:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x86
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements_cli.txt
      - name: Build Porn Fetch (CLI - Windows - X32) (PyInstaller)
        run: |
          pyinstaller -F Porn_Fetch_CLI.py

      - name: Archive Porn Fetch CLI (Windows X32) build
        uses: actions/upload-artifact@v2
        with:
          name: PornFetch_CLI_Linux_x32
          path: dist/Porn_Fetch_CLI.exe

  build-pornfetch-cli-linux-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements_cli.txt ]; then pip install -r requirements.txt; fi
      - name: Build Porn Fetch (CLI) (PyInstaller - Termux)
        run: |
          pyinstaller -F Porn_Fetch_CLI.py && cd dist && chmod +x Porn_Fetch_CLI

      - name: Archive Porn Fetch CLI (Linux_64) build
        uses: actions/upload-artifact@v2
        with:
          name: PornFetch_CLI_Linux_x64
          path: dist/Porn_Fetch_CLI

  build-pornfetch-cli-linux-32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies for building Python
        run: |
          sudo apt-get update
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib libffi-dev libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev binutils-dev
          sudo apt-get install -y libfl-dev libncurses5:i386 libncursesw5:i386 libtinfo5:i386 zlib1g:i386 zlib1g-dev:i386 openssl:i386 libssl-dev:i386 openssl libssl-dev
      - name: Download and build Python 3.11 for x32
        run: |
          wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
          tar -xzf Python-3.11.0.tgz
          cd Python-3.11.0
          CFLAGS="-m32" LDFLAGS="-m32" ./configure --prefix=/usr/local/python-32 --with-ensurepip=install --with-openssl=/usr/lib/i386-linux-gnu
          make -j $(nproc)
          sudo make altinstall
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: Install Python packages
        run: |
          /usr/local/python-32/bin/python3.11 -m pip install --upgrade pip
          /usr/local/python-32/bin/pip install pyinstaller
          if [ -f requirements_cli.txt ]; then /usr/local/python-32/bin/pip install -r requirements_cli.txt; fi

      - name: Build Porn Fetch (CLI) (PyInstaller - Termux)
        run: |
          /usr/local/python-32/bin/pyinstaller -F --paths /usr/local/python-32/lib/python3.11/site-packages Porn_Fetch_CLI.py
          cd dist
          chmod +x Porn_Fetch_CLI

      - name: Archive Porn Fetch CLI (Linux_32) build
        uses: actions/upload-artifact@v2
        with:
          name: PornFetch_CLI_Linux_x32
          path: dist/Porn_Fetch_CLI
