name: Build PySide6 Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application for x64
        run: |
          mkdir deploy
          shopt -s extglob
          mv !(deploy|venv) deploy/  # Ensure venv is not moved
          cd deploy
          pwd
          ls -la
          source ../venv/bin/activate
          pyside6-deploy

      - name: Archive x64 build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-x64
          path: deploy/main.bin

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application
        run: |
          mkdir deploy
          shopt -s extglob
          mv !(deploy|venv) deploy/
          cd deploy
          source ../venv/bin/activate
          pyside6-deploy

      - name: List output directory
        run: |
          ls -R deploy/

      - name: Archive macOS build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-macos
          path: deploy/pyside_app_demo.app

  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          .\\venv\\Scripts\\activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application for Windows x64
        run: |
          mkdir deploy
          Get-ChildItem -Path . -Exclude deploy,venv | Move-Item -Destination deploy
          cd deploy
          ..\venv\Scripts\activate
          echo "yes" | pyside6-deploy --extra-modules=QtCore,QtWidgets,QtGui

      - name: Archive Windows x64 build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-windows-x64
          path: deploy/main.exe
