# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa xvfb
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --upgrade git+https://github.com/Egsagon/PHUB.git
    - name: Build with Pyinstaller
      run: |
        pyinstaller -F Porn_Fetch.py && cd dist && chmod +x Porn_Fetch && xvfb-run ./Porn_Fetch --version
    - name: Build CLI (Termux Test)
      run: | 
        cd src && pyinstaller -F cli.py && cd dist && chmod +x cli